cc_binary(
    name = "spectral_inspector",
    srcs = ["spectral_inspector.cc"],
    deps = [
        "//libballistae:color",
        "//libballistae:spectral_image",
        "//third_party/cc/absl/absl/flags:flag",
        "//third_party/cc/absl/absl/flags:parse",
        "//third_party/cc/absl/absl/strings:str_format",
    ],
)
