cc_library(
    name = "material",
    deps = [
        ":directional_emitter",
        ":emitter",
        ":gauss",
        ":mc_lambert",
        ":nc_smooth",
        ":normal_highlighter",
        ":pc_smooth",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "directional_emitter",
    hdrs = ["directional_emitter.hh"],
)

cc_library(
    name = "emitter",
    hdrs = ["emitter.hh"],
)

cc_library(
    name = "gauss",
    hdrs = ["gauss.hh"],
)

cc_library(
    name = "mc_lambert",
    hdrs = ["mc_lambert.hh"],
)

cc_library(
    name = "nc_smooth",
    hdrs = ["nc_smooth.hh"],
)

cc_library(
    name = "normal_highlighter",
    hdrs = ["normal_highlighter.hh"],
)

cc_library(
    name = "pc_smooth",
    hdrs = ["pc_smooth.hh"],
)
