cc_library(
    name = "affine_transform",
    hdrs = ["affine_transform.hh"],
    visibility = ["//visibility:public"],
    deps = ["//frustum/indicial"],
    copts = [
        "--std=c++17",
    ],
)
